arguments:
  parameters:
    - name: application-name-dev
      value: testapp-dev
    - name: application-name-stag
      value: testapp-staging
    - name: revision
      value: main
    - name: argocd-server-address
      value: argocd.apps.argoproj.io
    - name: argocd-credentials-secret
      value: argocd-user
