apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlastestapp-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mihirpandya-greenops/atlas-playground.git
    targetRevision: main
    path: deployment-manifest/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
